server:
  port: 9191

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true



logging:
  level:
    org:
      hibernate:
        type: debug